### ISSUE TITLE
.gitlab-ci.yml fails to validate because of "unknown tag !reference"

### ISSUE THREAD

**Issue by 749** [chris48s/v8r#458]
A gitlab-ci file may contain the following construct to include parts of another job in the current job.

`example.gitlab-ci.yml`
```yaml
.build-shell-options:
  before_script:
    - set -euo pipefail

.alpine-install-gitlab-essentials:
  before_script:
    - !reference [.build-shell-options, before_script]
    - 'echo "BEGIN: .alpine-install-gitlab-essentials:before_script"'
```

See also the GitLab docs: https://docs.gitlab.com/ee/ci/yaml/yaml_optimization.html#reference-tags

Unfortunately this causes an error similar to:
```log
ℹ Validating ./example.gitlab-ci.yml against schema from https://gitlab.com/gitlab-org/gitlab/-/raw/master/app/assets/javascripts/editor/schema/ci.json ...
✖ unknown tag !<!reference> (30:55)

 29 |  ... 
 30 |  ... -shell-options, before_script]
-----------------------------------------^
 31 |  ... ine-install-gitlab-essentials:before_script"'
```

Thanks for looking into the problem! 👍
